on:
  push:
    branches: master

name: Pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 4.0
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "install.packages('devtools')"
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: Cache dependencies
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.local/share/renv
          key: ubuntu-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ubuntu-renv-
      - name: Install dependencies
        run: |
          renv::install()
        shell: Rscript {0}
      - name: Install package
        run: R CMD INSTALL --no-multiarch --with-keep.source .

      - name: Build pkgdown site
        run: |
          devtools::document(roclets = c('rd', 'collate', 'namespace', 'vignette'))
          pkgdown::build_site(new_process = FALSE)
        shell: Rscript {0}

      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs
        with:
          emptyCommits: false